{% set version = "7.0.2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-roxygen2
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/roxygen2_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/roxygen2/roxygen2_{{ version }}.tar.gz
  sha256: 5823937df68ea558e5e85771b8b6e090775b82f7f797ca5d539e7378c4535d98

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('m2w64_cxx') }}        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-r6 >=2.1.2
    - r-rcpp >=0.11.0
    - r-brew
    - r-commonmark
    - r-desc >=1.2.0
    - r-digest
    - r-pkgload >=1.0.2
    - r-purrr
    - r-stringi
    - r-stringr >=1.0.0
    - r-xml2
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-r6 >=2.1.2
    - r-rcpp >=0.11.0
    - r-brew
    - r-commonmark
    - r-desc >=1.2.0
    - r-digest
    - r-pkgload >=1.0.2
    - r-purrr
    - r-stringi
    - r-stringr >=1.0.0
    - r-xml2

test:
  commands:
    - $R -e "library('roxygen2')"           # [not win]
    - "\"%R%\" -e \"library('roxygen2')\""  # [win]

about:
  home: https://github.com/klutometis/roxygen
  license: GPL (>= 2)
  summary: Generate your Rd documentation, 'NAMESPACE' file, and collation  field using specially
    formatted comments. Writing documentation in-line with code makes it easier to keep
    your documentation up-to-date as your requirements change. 'Roxygen2' is inspired
    by the 'Doxygen' system for C++.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: roxygen2
# Title: In-Line Documentation for R
# Version: 6.1.1
# Authors@R: c( person("Hadley", "Wickham",, "hadley@rstudio.com", c("aut", "cre", "cph")), person("Peter", "Danenberg",, "pcd@roxygen.org", c("aut", "cph")), person("Manuel", "Eugster", role = c("aut", "cph")), person("RStudio", role = "cph") )
# Description: Generate your Rd documentation, 'NAMESPACE' file, and collation  field using specially formatted comments. Writing documentation in-line with code makes it easier to keep your documentation up-to-date as your requirements change. 'Roxygen2' is inspired by the 'Doxygen' system for C++.
# License: GPL (>= 2)
# URL: https://github.com/klutometis/roxygen
# BugReports: https://github.com/klutometis/roxygen/issues
# Depends: R (>= 3.1)
# Imports: brew, commonmark, desc (>= 1.2.0), digest, methods, pkgload (>= 1.0.2), purrr, R6 (>= 2.1.2), Rcpp (>= 0.11.0), stringi, stringr (>= 1.0.0), utils, xml2
# Suggests: covr, devtools, knitr, rmarkdown, testthat (>= 0.8.0)
# LinkingTo: Rcpp
# VignetteBuilder: knitr
# Encoding: UTF-8
# RoxygenNote: 6.1.1
# NeedsCompilation: yes
# Packaged: 2018-11-06 23:40:35 UTC; hadley
# Author: Hadley Wickham [aut, cre, cph], Peter Danenberg [aut, cph], Manuel Eugster [aut, cph], RStudio [cph]
# Maintainer: Hadley Wickham <hadley@rstudio.com>
# Repository: CRAN
# Date/Publication: 2018-11-07 05:40:12 UTC
