appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  linux_aarch64: default
  linux_ppc64le: azure
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: A48uwm4mBkX5oWDgl2ebvEv+e9AQ+SvisirlsWj0iWlQN9Repe7sdCUfn3SXFDfnc8zZtV/YYbPGo00Ls2oAE5lmi13dXcWmcfgCtOk0pAIutm9bSIsa7ON2yOPxtuPnX6g3u12qmyuIfl1QsbDD+U6SdJ+6PrzFcuMD7bwTscYr8n80CbYWaefEH8lD6jpkeBYqdwoN95RrqNftGTKiXDcSHpgH9EcDINYDxPng1VdAVr3I2WpV2P6asBjXyzosKfJ3APO+ibJDQjrHW2/xGGrXc7ahK9VViFZw2FfqSh2OdH3SRBcwBwgN+fphP4uCuZb6NbcU6JDxTsUDy4HLYwgnZqZMa8buKAeC6TKPN3TqA8FP2qSz2pycURru9JLzRWg5v3H8ZeVwnFp+Xo5GuQ8R1tb2jxv1sGNb78dwSQ9plw5rvd+DdXmbQ1FYUSi/7jrowfBrb9w0a8x3Ip+ZL7FeZrPw6nbe16pcwmHMMB/iuj0Qzrx+4Zr5BSVLbPsFvsyhjepyb3cilYyuidFRlXSWP3BA+aA4rZ9lTD0gFEMcNeqDsKwSPDnaWV7sh4Xk53riLbrcy8zZ1tZ22a2jnbBDL2LovU+pxTqiPqLx926uxy+q84iIXw+UA/5thoAHySWz0DWNxexzM94gWWsyCodiY7JgMFnnWAC21BVzvi8=
